version: '3.3'

services:

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - front_net
      - back_net

  rabbit:
    image: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - front_net
      - back_net

  ui:
    image: jugatsu/search_engine_ui
    ports:
      - "8000:8000"
    networks:
      - front_net

volumes:
  mongo_data: {}
  rabbitmq_data: {}

networks:
  back_net: {}
  front_net: {}
